"""init schema

Revision ID: e17ec0f04b83
Revises: 
Create Date: 2026-08-20 18:29:33.444527+07:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'e17ec0f04b83'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('role', sa.Enum('admin', 'merchant', name='userrole', native_enum=False, length=32), server_default='merchant', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_user_created_at'), 'app_user', ['created_at'], unique=False)
    op.create_index(op.f('ix_app_user_email'), 'app_user', ['email'], unique=True)
    op.create_table('attribute',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('group_name', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_name', 'name', name='uq_attribute_group_name')
    )
    op.create_index(op.f('ix_attribute_created_at'), 'attribute', ['created_at'], unique=False)
    op.create_index(op.f('ix_attribute_group_name'), 'attribute', ['group_name'], unique=False)
    op.create_index(op.f('ix_attribute_slug'), 'attribute', ['slug'], unique=True)
    op.create_table('category',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('level', sa.Enum('master', 'sub', 'article', name='categorylevel', native_enum=False, length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=96), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('item_slot', sa.Enum('top', 'bottom', 'outerwear', 'full_body', 'footwear', 'headwear', 'eyewear', 'accessory', name='itemslot', native_enum=False, length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['category.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'name', name='uq_category_parent_name')
    )
    op.create_index(op.f('ix_category_created_at'), 'category', ['created_at'], unique=False)
    op.create_index('ix_category_level_active', 'category', ['level', 'is_active'], unique=False)
    op.create_index(op.f('ix_category_parent_id'), 'category', ['parent_id'], unique=False)
    op.create_index(op.f('ix_category_slug'), 'category', ['slug'], unique=True)
    op.create_table('colour',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('slug', sa.String(length=48), nullable=False),
    sa.Column('hex_code', sa.String(length=7), nullable=False),
    sa.Column('lab_l', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('lab_a', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('lab_b', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('is_neutral', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_colour_created_at'), 'colour', ['created_at'], unique=False)
    op.create_index(op.f('ix_colour_slug'), 'colour', ['slug'], unique=True)
    op.create_table('measurement_key',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('key', sa.String(length=48), nullable=False),
    sa.Column('label', sa.String(length=96), nullable=False),
    sa.Column('unit', sa.Enum('cm', 'kg', 'ratio', name='measurementunit', native_enum=False, length=32), nullable=False),
    sa.Column('body_part', sa.String(length=32), nullable=True),
    sa.Column('is_core', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_measurement_key_created_at'), 'measurement_key', ['created_at'], unique=False)
    op.create_index(op.f('ix_measurement_key_key'), 'measurement_key', ['key'], unique=True)
    op.create_table('question_batch',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('order_index', sa.SmallInteger(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unlocks_slots', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('order_index >= 0', name='ck_question_batch_order'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_batch_code'), 'question_batch', ['code'], unique=True)
    op.create_index(op.f('ix_question_batch_created_at'), 'question_batch', ['created_at'], unique=False)
    op.create_index('ix_question_batch_order', 'question_batch', ['order_index', 'is_active'], unique=False)
    op.create_table('anthropometry_reference',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('measurement_key_id', sa.BigInteger(), nullable=False),
    sa.Column('gender', sa.Enum('men', 'women', 'boys', 'girls', 'unisex', name='gender', native_enum=False, length=32), nullable=False),
    sa.Column('age_min', sa.SmallInteger(), nullable=False),
    sa.Column('age_max', sa.SmallInteger(), nullable=False),
    sa.Column('percentile', sa.SmallInteger(), nullable=False),
    sa.Column('value_cm', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('source_year', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('age_min <= age_max', name='ck_anthropometry_age_range'),
    sa.CheckConstraint('percentile IN (5, 50, 95)', name='ck_anthropometry_percentile'),
    sa.ForeignKeyConstraint(['measurement_key_id'], ['measurement_key.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('measurement_key_id', 'gender', 'age_min', 'age_max', 'percentile', name='uq_anthropometry_reference')
    )
    op.create_index(op.f('ix_anthropometry_reference_created_at'), 'anthropometry_reference', ['created_at'], unique=False)
    op.create_index(op.f('ix_anthropometry_reference_measurement_key_id'), 'anthropometry_reference', ['measurement_key_id'], unique=False)
    op.create_table('question',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('batch_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('order_index', sa.SmallInteger(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('input_type', sa.Enum('single_choice', 'multi_choice', 'boolean', 'scale', name='questioninputtype', native_enum=False, length=32), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('maps_to', sa.String(length=48), nullable=False),
    sa.Column('is_required', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("jsonb_typeof(options) = 'array'", name='ck_question_options_array'),
    sa.ForeignKeyConstraint(['batch_id'], ['question_batch.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_question_batch_id_order', 'question', ['batch_id', 'order_index'], unique=False)
    op.create_index(op.f('ix_question_code'), 'question', ['code'], unique=True)
    op.create_index(op.f('ix_question_created_at'), 'question', ['created_at'], unique=False)
    op.create_index(op.f('ix_question_maps_to'), 'question', ['maps_to'], unique=False)
    op.create_table('refresh_token',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('jti', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_jti', sa.String(length=32), nullable=True),
    sa.Column('user_agent_hash', sa.String(length=64), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_token_created_at'), 'refresh_token', ['created_at'], unique=False)
    op.create_index('ix_refresh_token_expires', 'refresh_token', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_token_jti'), 'refresh_token', ['jti'], unique=True)
    op.create_index('ix_refresh_token_user_active', 'refresh_token', ['user_id', 'revoked_at'], unique=False)
    op.create_table('size_chart',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('version', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('region', sa.String(length=8), server_default='ID', nullable=False),
    sa.Column('gender', sa.Enum('men', 'women', 'boys', 'girls', 'unisex', name='gender', native_enum=False, length=32), nullable=True),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('merchant_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['merchant_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'version', name='uq_size_chart_code_version')
    )
    op.create_index(op.f('ix_size_chart_code'), 'size_chart', ['code'], unique=False)
    op.create_index(op.f('ix_size_chart_created_at'), 'size_chart', ['created_at'], unique=False)
    op.create_index('ix_size_chart_lookup', 'size_chart', ['category_id', 'gender', 'region', 'is_active'], unique=False)
    op.create_table('style_rule',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('subject', sa.Enum('body_shape', 'face_shape', 'undertone', 'fit_preference', 'occasion', name='rulesubject', native_enum=False, length=32), nullable=False),
    sa.Column('subject_value', sa.String(length=32), nullable=False),
    sa.Column('target_category_id', sa.BigInteger(), nullable=True),
    sa.Column('target_attribute_id', sa.BigInteger(), nullable=True),
    sa.Column('target_colour_id', sa.BigInteger(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=16), server_default='stylist', nullable=False),
    sa.Column('model_version', sa.String(length=48), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('num_nonnulls(target_category_id, target_attribute_id, target_colour_id) = 1', name='ck_style_rule_single_target'),
    sa.CheckConstraint('weight BETWEEN -1 AND 1', name='ck_style_rule_weight'),
    sa.ForeignKeyConstraint(['target_attribute_id'], ['attribute.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_category_id'], ['category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_colour_id'], ['colour.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_style_rule_created_at'), 'style_rule', ['created_at'], unique=False)
    op.create_index('ix_style_rule_subject', 'style_rule', ['subject', 'subject_value', 'is_active'], unique=False)
    op.create_index('uq_style_rule_target', 'style_rule', ['subject', 'subject_value', 'target_category_id', 'target_attribute_id', 'target_colour_id'], unique=True, postgresql_nulls_not_distinct=True)
    op.create_table('undertone_palette',
    sa.Column('undertone', sa.Enum('warm', 'cool', 'neutral', 'olive', name='undertone', native_enum=False, length=32), nullable=False),
    sa.Column('colour_id', sa.BigInteger(), nullable=False),
    sa.Column('affinity', sa.Enum('recommended', 'neutral', 'avoid', name='colouraffinity', native_enum=False, length=32), nullable=False),
    sa.Column('weight', sa.Float(), server_default='0', nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('weight BETWEEN -1 AND 1', name='ck_palette_weight'),
    sa.ForeignKeyConstraint(['colour_id'], ['colour.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('undertone', 'colour_id')
    )
    op.create_index(op.f('ix_undertone_palette_created_at'), 'undertone_palette', ['created_at'], unique=False)
    op.create_table('product',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.Enum('men', 'women', 'boys', 'girls', 'unisex', name='gender', native_enum=False, length=32), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('colour_id', sa.BigInteger(), nullable=True),
    sa.Column('usage_context', sa.Enum('casual', 'formal', 'sports', 'ethnic', 'party', 'smart_casual', 'travel', 'home', name='usagecontext', native_enum=False, length=32), nullable=True),
    sa.Column('season', sa.Enum('summer', 'fall', 'winter', 'spring', name='season', native_enum=False, length=32), nullable=True),
    sa.Column('launch_year', sa.SmallInteger(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('price_idr', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('merchant_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('size_chart_id', sa.BigInteger(), nullable=True),
    sa.Column('popularity_score', sa.Float(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple', coalesce(display_name, ''))", persisted=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('launch_year IS NULL OR launch_year BETWEEN 1990 AND 2100', name='ck_product_launch_year'),
    sa.CheckConstraint('price_idr IS NULL OR price_idr >= 0', name='ck_product_price_positive'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['colour_id'], ['colour.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['merchant_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['size_chart_id'], ['size_chart.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index(op.f('ix_product_category_id'), 'product', ['category_id'], unique=False)
    op.create_index('ix_product_colour', 'product', ['colour_id'], unique=False)
    op.create_index(op.f('ix_product_created_at'), 'product', ['created_at'], unique=False)
    op.create_index('ix_product_keyset', 'product', ['popularity_score', 'id'], unique=False)
    op.create_index('ix_product_merchant', 'product', ['merchant_id'], unique=False)
    op.create_index('ix_product_reco_filter', 'product', ['gender', 'usage_context', 'category_id'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_index('ix_product_search', 'product', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_table('size_chart_entry',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('size_chart_id', sa.BigInteger(), nullable=False),
    sa.Column('size_label', sa.String(length=12), nullable=False),
    sa.Column('sort_order', sa.SmallInteger(), nullable=False),
    sa.Column('measurement_key_id', sa.BigInteger(), nullable=False),
    sa.Column('min_value', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('max_value', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.CheckConstraint('min_value <= max_value', name='ck_size_chart_entry_range'),
    sa.CheckConstraint('min_value >= 0', name='ck_size_chart_entry_positive'),
    sa.ForeignKeyConstraint(['measurement_key_id'], ['measurement_key.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['size_chart_id'], ['size_chart.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('size_chart_id', 'size_label', 'measurement_key_id', name='uq_size_chart_entry')
    )
    op.create_index('ix_size_chart_entry_chart', 'size_chart_entry', ['size_chart_id', 'sort_order'], unique=False)
    op.create_table('asset_3d',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('size_label', sa.String(length=12), nullable=True),
    sa.Column('lod', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('format', sa.Enum('glb', 'gltf', 'usdz', name='assetformat', native_enum=False, length=32), server_default='glb', nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('license_code', sa.Enum('cc0', 'cc_by', 'cc_by_sa', 'cc_by_nc', 'mit', 'apache_2_0', 'proprietary', name='licensecode', native_enum=False, length=32), nullable=False),
    sa.Column('attribution', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('generated_by', sa.String(length=48), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('file_size_bytes IS NULL OR file_size_bytes > 0', name='ck_asset_file_size'),
    sa.CheckConstraint('lod BETWEEN 0 AND 3', name='ck_asset_lod'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'size_label', 'lod', 'format', name='uq_asset_variant')
    )
    op.create_index(op.f('ix_asset_3d_created_at'), 'asset_3d', ['created_at'], unique=False)
    op.create_index('ix_asset_license', 'asset_3d', ['license_code'], unique=False)
    op.create_index('ix_asset_product_active', 'asset_3d', ['product_id', 'is_active'], unique=False)
    op.create_table('product_attribute',
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('attribute_id', sa.BigInteger(), nullable=False),
    sa.Column('confidence', sa.Float(), server_default='1.0', nullable=False),
    sa.Column('source', sa.String(length=16), server_default='dataset', nullable=False),
    sa.Column('model_version', sa.String(length=48), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence BETWEEN 0 AND 1', name='ck_product_attribute_confidence'),
    sa.ForeignKeyConstraint(['attribute_id'], ['attribute.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'attribute_id')
    )
    op.create_index('ix_product_attribute_attr', 'product_attribute', ['attribute_id'], unique=False)
    op.create_index(op.f('ix_product_attribute_created_at'), 'product_attribute', ['created_at'], unique=False)
    op.create_table('recommendation_feedback_daily',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('body_shape', sa.Enum('hourglass', 'pear', 'apple', 'rectangle', 'inverted_triangle', name='bodyshape', native_enum=False, length=32), nullable=True),
    sa.Column('undertone', sa.Enum('warm', 'cool', 'neutral', 'olive', name='undertone', native_enum=False, length=32), nullable=True),
    sa.Column('occasion', sa.Enum('casual', 'formal', 'sports', 'ethnic', 'party', 'smart_casual', 'travel', 'home', name='usagecontext', native_enum=False, length=32), nullable=True),
    sa.Column('impressions', sa.Integer(), server_default='0', nullable=False),
    sa.Column('likes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('dislikes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('likes >= 0 AND dislikes >= 0 AND impressions >= 0', name='ck_feedback_counts'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feedback_product_day', 'recommendation_feedback_daily', ['product_id', 'day'], unique=False)
    op.create_index(op.f('ix_recommendation_feedback_daily_created_at'), 'recommendation_feedback_daily', ['created_at'], unique=False)
    op.create_index('uq_feedback_slice', 'recommendation_feedback_daily', ['day', 'product_id', 'body_shape', 'undertone', 'occasion'], unique=True, postgresql_nulls_not_distinct=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_feedback_slice', table_name='recommendation_feedback_daily', postgresql_nulls_not_distinct=True)
    op.drop_index(op.f('ix_recommendation_feedback_daily_created_at'), table_name='recommendation_feedback_daily')
    op.drop_index('ix_feedback_product_day', table_name='recommendation_feedback_daily')
    op.drop_table('recommendation_feedback_daily')
    op.drop_index(op.f('ix_product_attribute_created_at'), table_name='product_attribute')
    op.drop_index('ix_product_attribute_attr', table_name='product_attribute')
    op.drop_table('product_attribute')
    op.drop_index('ix_asset_product_active', table_name='asset_3d')
    op.drop_index('ix_asset_license', table_name='asset_3d')
    op.drop_index(op.f('ix_asset_3d_created_at'), table_name='asset_3d')
    op.drop_table('asset_3d')
    op.drop_index('ix_size_chart_entry_chart', table_name='size_chart_entry')
    op.drop_table('size_chart_entry')
    op.drop_index('ix_product_search', table_name='product', postgresql_using='gin')
    op.drop_index('ix_product_reco_filter', table_name='product', postgresql_where=sa.text('is_active = true'))
    op.drop_index('ix_product_merchant', table_name='product')
    op.drop_index('ix_product_keyset', table_name='product')
    op.drop_index(op.f('ix_product_created_at'), table_name='product')
    op.drop_index('ix_product_colour', table_name='product')
    op.drop_index(op.f('ix_product_category_id'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_undertone_palette_created_at'), table_name='undertone_palette')
    op.drop_table('undertone_palette')
    op.drop_index('uq_style_rule_target', table_name='style_rule', postgresql_nulls_not_distinct=True)
    op.drop_index('ix_style_rule_subject', table_name='style_rule')
    op.drop_index(op.f('ix_style_rule_created_at'), table_name='style_rule')
    op.drop_table('style_rule')
    op.drop_index('ix_size_chart_lookup', table_name='size_chart')
    op.drop_index(op.f('ix_size_chart_created_at'), table_name='size_chart')
    op.drop_index(op.f('ix_size_chart_code'), table_name='size_chart')
    op.drop_table('size_chart')
    op.drop_index('ix_refresh_token_user_active', table_name='refresh_token')
    op.drop_index(op.f('ix_refresh_token_jti'), table_name='refresh_token')
    op.drop_index('ix_refresh_token_expires', table_name='refresh_token')
    op.drop_index(op.f('ix_refresh_token_created_at'), table_name='refresh_token')
    op.drop_table('refresh_token')
    op.drop_index(op.f('ix_question_maps_to'), table_name='question')
    op.drop_index(op.f('ix_question_created_at'), table_name='question')
    op.drop_index(op.f('ix_question_code'), table_name='question')
    op.drop_index('ix_question_batch_id_order', table_name='question')
    op.drop_table('question')
    op.drop_index(op.f('ix_anthropometry_reference_measurement_key_id'), table_name='anthropometry_reference')
    op.drop_index(op.f('ix_anthropometry_reference_created_at'), table_name='anthropometry_reference')
    op.drop_table('anthropometry_reference')
    op.drop_index('ix_question_batch_order', table_name='question_batch')
    op.drop_index(op.f('ix_question_batch_created_at'), table_name='question_batch')
    op.drop_index(op.f('ix_question_batch_code'), table_name='question_batch')
    op.drop_table('question_batch')
    op.drop_index(op.f('ix_measurement_key_key'), table_name='measurement_key')
    op.drop_index(op.f('ix_measurement_key_created_at'), table_name='measurement_key')
    op.drop_table('measurement_key')
    op.drop_index(op.f('ix_colour_slug'), table_name='colour')
    op.drop_index(op.f('ix_colour_created_at'), table_name='colour')
    op.drop_table('colour')
    op.drop_index(op.f('ix_category_slug'), table_name='category')
    op.drop_index(op.f('ix_category_parent_id'), table_name='category')
    op.drop_index('ix_category_level_active', table_name='category')
    op.drop_index(op.f('ix_category_created_at'), table_name='category')
    op.drop_table('category')
    op.drop_index(op.f('ix_attribute_slug'), table_name='attribute')
    op.drop_index(op.f('ix_attribute_group_name'), table_name='attribute')
    op.drop_index(op.f('ix_attribute_created_at'), table_name='attribute')
    op.drop_table('attribute')
    op.drop_index(op.f('ix_app_user_email'), table_name='app_user')
    op.drop_index(op.f('ix_app_user_created_at'), table_name='app_user')
    op.drop_table('app_user')
    # ### end Alembic commands ###
